options:
  formatter: table
files:
  include:
    - 'app/scss/**/*.scss'
  ignore:
    - 'node_modules/**/*.scss'
rules:
  bem-depth: 2
  border-zero: 0
  brace-style: 2
  class-name-format:
    - 2
    - convention: hyphenatedbem
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  # These 3 rules can be overridden per file until we have time to rewrite
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  max-line-length: 0
  mixin-name-format: 2
  mixins-before-declarations:
    - 2
    - exclude: ['bp']
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 0
  no-color-literals: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-misspelled-properties:
    - 2
    - 'extra-properties':
      - 'user-drag'
      - '-ms-align-content'
      - '-ms-align-items'
      - '-ms-align-self'
      - '-ms-justify-content'
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order: 2
  pseudo-element: 0
  quotes: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 2
  zero-unit: 2
